name: Publish Release

on:
  push:
    branches: [ release/* ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: europe-west1

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Setup GCloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '298.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Copy files to GCloud Bucket
        run: gsutil cp ./*.xsd  gs://schema.cip4.org/jdfschema_1_${GITHUB_REF##*JDF_1.}

      - name: Create ZIP Archive
        run: zip jdfschema_1_${GITHUB_REF##*JDF_1.}.zip *.xsd

      - name: Copy ZIP Archive to GCloud Bucket
        run: gsutil cp ./*.zip  gs://schema.cip4.org/

      - name: Createa tar.gz Archive
        run: tar -czvf jdfschema_1_${GITHUB_REF##*JDF_1.}.tar.gz *.xsd

      - name: Copy tar.gz Archive to GCloud Bucket
        run: gsutil cp ./*.tar.gz  gs://schema.cip4.org/
