name: Publish Snapshot (DEV Version)

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: europe-west1

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Update Parameters
        run: |
          NOW=$(TZ=GMT date +"%Y-%m-%d %H:%M:%SZ")
          SPEC_VERSION=1.x
          VERSION=${SPEC_VERSION}.${GITHUB_RUN_NUMBER}-SNAPSHOT-${GITHUB_SHA:0:7}
          sed -i "s|@@branch@@|${GITHUB_REF#refs/heads/}|g" *.xsd
          sed -i "s|@@version@@|${VERSION}|g" *.xsd
          sed -i "s|@@buildTime@@|${NOW}|g" *.xsd
          echo "{ \"buildTime\": \"${NOW}\", \"version\": \"${VERSION}\", \"specVersion\": \"${SPEC_VERSION}\" }" > version.json

      - name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Copy files to GCloud Bucket
        run: |
          gsutil cp ./*.xsd gs://schema.cip4.org/jdfschema_1_x/
          gsutil cp ./version.json gs://schema.cip4.org/jdfschema_1_x/

      - name: Create ZIP Archive
        run: zip jdfschema_1_x.zip *.xsd version.json LICENSE.md

      - name: Copy ZIP Archive to GCloud Bucket
        run: gsutil cp ./*.zip  gs://schema.cip4.org/

      - name: Createa tar.gz Archive
        run: tar -czvf jdfschema_1_x.tar.gz *.xsd version.json LICENSE.md

      - name: Copy tar.gz Archive to GCloud Bucket
        run: gsutil cp ./*.tar.gz  gs://schema.cip4.org/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xsd-artifacts
          path: '*.xsd'

      - name: Invalidate CDN Cache
        run: gcloud compute url-maps invalidate-cdn-cache cip4-public-balancer --path "/jdfschema_1_x/*"
