name: Verify Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources...
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: Verify
        run: ./gradlew test --no-daemon